#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TI_TASK 0 /* offsetof(struct thread_info, task)	! */
#define TI_EXEC_DOMAIN 4 /* offsetof(struct thread_info, exec_domain)	! */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	! */
#define TI_CPU 12 /* offsetof(struct thread_info, cpu)	! */
#define TI_PRE_COUNT 16 /* offsetof(struct thread_info, preempt_count)	! */
#define TI_RESTART_BLOCK 24 /* offsetof(struct thread_info, restart_block)	! */

#endif
